import { useState } from "react";
import { useInterviewStore, type AttemptResult, type ModuleType } from "@/stores/interviewStore";
import { Download, Copy, Check } from "lucide-react";
import { cn } from "@/lib/utils";

const moduleLabels: Record<ModuleType, string> = {
  "cv-screening": "CV Screening",
  "voice-interview": "Voice Interview",
  "technical-interview": "Technical Interview",
};

function formatDuration(seconds?: number): string {
  if (!seconds) return "";
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}m ${s}s`;
}

function buildExportText(attempts: AttemptResult[]): string {
  const lines: string[] = [];

  lines.push("═══════════════════════════════════════════");
  lines.push("  INTERVIEW PREPARATION — RESULTS SUMMARY");
  lines.push("═══════════════════════════════════════════");
  lines.push("");
  lines.push(`Exported: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  lines.push(`Total attempts: ${attempts.length}`);
  lines.push("");

  const byModule = new Map<ModuleType, AttemptResult[]>();
  for (const a of attempts) {
    const list = byModule.get(a.module) || [];
    list.push(a);
    byModule.set(a.module, list);
  }

  for (const [module, moduleAttempts] of byModule) {
    const label = moduleLabels[module];
    lines.push(`─── ${label.toUpperCase()} (${ moduleAttempts.length} attempt${moduleAttempts.length > 1 ? "s" : ""}) ───`);
    lines.push("");

    for (const attempt of moduleAttempts) {
      const pct = attempt.maxScore > 0 ? Math.round((attempt.overallScore / attempt.maxScore) * 100) : 0;
      const date = new Date(attempt.date).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
      });
      const dur = formatDuration(attempt.duration);
      const role = attempt.jobRole || "";

      lines.push(`  Score: ${attempt.overallScore}/${attempt.maxScore} (${pct}%)  |  ${date}${dur ? `  |  ${dur}` : ""}${role ? `  |  ${role}` : ""}`);

      if (attempt.feedback.length > 0) {
        lines.push("  Breakdown:");
        for (const fb of attempt.feedback) {
          const fbPct = fb.maxScore > 0 ? Math.round((fb.score / fb.maxScore) * 100) : 0;
          lines.push(`    • ${fb.category}: ${fb.score}/${fb.maxScore} (${fbPct}%)`);
          if (fb.comment) {
            lines.push(`      ${fb.comment}`);
          }
          if (fb.suggestions.length > 0) {
            for (const sug of fb.suggestions) {
              lines.push(`      → ${sug}`);
            }
          }
        }
      }
      lines.push("");
    }
  }

  // Overall summary
  if (byModule.size > 0) {
    lines.push("─── OVERALL ───");
    lines.push("");
    const latestByModule = new Map<ModuleType, AttemptResult>();
    for (const [mod, modAttempts] of byModule) {
      latestByModule.set(mod, modAttempts[0]);
    }
    let totalScore = 0;
    let totalMax = 0;
    for (const [mod, latest] of latestByModule) {
      totalScore += latest.overallScore;
      totalMax += latest.maxScore;
      const pct = latest.maxScore > 0 ? Math.round((latest.overallScore / latest.maxScore) * 100) : 0;
      lines.push(`  ${moduleLabels[mod]}: ${pct}%`);
    }
    if (totalMax > 0) {
      lines.push(`  Combined: ${Math.round((totalScore / totalMax) * 100)}%`);
    }
    lines.push("");
  }

  lines.push("Generated by Vortex Interview Prep");
  return lines.join("\n");
}

export function ExportResults() {
  const { attempts } = useInterviewStore();
  const [copied, setCopied] = useState(false);

  if (attempts.length === 0) return null;

  const exportText = buildExportText(attempts);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(exportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([exportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `interview-results-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex gap-2">
      <button
        type="button"
        onClick={handleCopy}
        className={cn(
          "inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-medium transition-all",
          copied
            ? "border-score-high/40 bg-score-high/10 text-score-high"
            : "border-border bg-card text-muted-foreground hover:bg-secondary hover:text-foreground",
        )}
      >
        {copied ? (
          <>
            <Check className="h-3.5 w-3.5" /> Copied
          </>
        ) : (
          <>
            <Copy className="h-3.5 w-3.5" /> Copy Summary
          </>
        )}
      </button>
      <button
        type="button"
        onClick={handleDownload}
        className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-2 text-xs font-medium text-muted-foreground transition-all hover:bg-secondary hover:text-foreground"
      >
        <Download className="h-3.5 w-3.5" /> Download .txt
      </button>
    </div>
  );
}
